from iota import Iota
from config import NODE_URL
import json

TXN_HASH = "XHADQXMPFWJCFCLZOVFYRFDQCNFLJFKVDRLCDACAOQBBQMMOUIVTPLASLOQAFRC9MUSUEFWPZJRMZ9999"
TIPS = "MITBRBFHTNDUMIQLLQWWXDCIELPCQMMYJTESPUYIH99YMHSWZXHYSAFCGFNIUCDSGJRUI9EFJCZHZ9999"

api = Iota(NODE_URL)
print(api.get_inclusion_states([TXN_HASH], [TIPS]))
